sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.4
jdk:
  - oraclejdk8
node_js:
  - "8"
services:
  - memcached
  - redis
script:
  - sbt ++$TRAVIS_SCALA_VERSION coreJVM/test:compile coreJS/test:compile coreJS/fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION coreJVM/test coreJS/test
  - sbt +test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
